#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libspatialindex
Version  : 1.8.5
Release  : 1
URL      : https://github.com/libspatialindex/libspatialindex/archive/1.8.5.tar.gz
Source0  : https://github.com/libspatialindex/libspatialindex/archive/1.8.5.tar.gz
Summary  : Generic C/C++ library for spatial indexing
Group    : Development/Tools
License  : MIT
Requires: libspatialindex-lib = %{version}-%{release}
Requires: libspatialindex-license = %{version}-%{release}
BuildRequires : buildreq-cmake

%description
*****************************************************************************
libspatialindex
*****************************************************************************

%package dev
Summary: dev components for the libspatialindex package.
Group: Development
Requires: libspatialindex-lib = %{version}-%{release}
Provides: libspatialindex-devel = %{version}-%{release}

%description dev
dev components for the libspatialindex package.


%package lib
Summary: lib components for the libspatialindex package.
Group: Libraries
Requires: libspatialindex-license = %{version}-%{release}

%description lib
lib components for the libspatialindex package.


%package license
Summary: license components for the libspatialindex package.
Group: Default

%description license
license components for the libspatialindex package.


%prep
%setup -q -n libspatialindex-1.8.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1545363615
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1545363615
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libspatialindex
cp COPYING %{buildroot}/usr/share/package-licenses/libspatialindex/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/spatialindex/LineSegment.h
/usr/include/spatialindex/MVRTree.h
/usr/include/spatialindex/MovingPoint.h
/usr/include/spatialindex/MovingRegion.h
/usr/include/spatialindex/Point.h
/usr/include/spatialindex/RTree.h
/usr/include/spatialindex/Region.h
/usr/include/spatialindex/SpatialIndex.h
/usr/include/spatialindex/TPRTree.h
/usr/include/spatialindex/TimePoint.h
/usr/include/spatialindex/TimeRegion.h
/usr/include/spatialindex/Version.h
/usr/include/spatialindex/capi/BoundsQuery.h
/usr/include/spatialindex/capi/CountVisitor.h
/usr/include/spatialindex/capi/CustomStorage.h
/usr/include/spatialindex/capi/DataStream.h
/usr/include/spatialindex/capi/Error.h
/usr/include/spatialindex/capi/IdVisitor.h
/usr/include/spatialindex/capi/Index.h
/usr/include/spatialindex/capi/LeafQuery.h
/usr/include/spatialindex/capi/ObjVisitor.h
/usr/include/spatialindex/capi/Utility.h
/usr/include/spatialindex/capi/sidx_api.h
/usr/include/spatialindex/capi/sidx_config.h
/usr/include/spatialindex/capi/sidx_export.h
/usr/include/spatialindex/capi/sidx_impl.h
/usr/include/spatialindex/tools/PointerPool.h
/usr/include/spatialindex/tools/PoolPointer.h
/usr/include/spatialindex/tools/SmartPointer.h
/usr/include/spatialindex/tools/Tools.h
/usr/include/spatialindex/tools/rand48.h
/usr/lib64/libspatialindex.so
/usr/lib64/libspatialindex_c.so
/usr/lib64/pkgconfig/libspatialindex.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libspatialindex.so.4
/usr/lib64/libspatialindex.so.4.0.1
/usr/lib64/libspatialindex_c.so.4
/usr/lib64/libspatialindex_c.so.4.0.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libspatialindex/COPYING
