#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libspatialindex
Version  : 1.9.3
Release  : 5
URL      : https://github.com/libspatialindex/libspatialindex/archive/1.9.3/libspatialindex-1.9.3.tar.gz
Source0  : https://github.com/libspatialindex/libspatialindex/archive/1.9.3/libspatialindex-1.9.3.tar.gz
Summary  : Generic C/C++ library for spatial indexing
Group    : Development/Tools
License  : BSD-3-Clause MIT
Requires: libspatialindex-lib = %{version}-%{release}
Requires: libspatialindex-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : glibc-dev
BuildRequires : python3

%description


%package dev
Summary: dev components for the libspatialindex package.
Group: Development
Requires: libspatialindex-lib = %{version}-%{release}
Provides: libspatialindex-devel = %{version}-%{release}
Requires: libspatialindex = %{version}-%{release}

%description dev
dev components for the libspatialindex package.


%package lib
Summary: lib components for the libspatialindex package.
Group: Libraries
Requires: libspatialindex-license = %{version}-%{release}

%description lib
lib components for the libspatialindex package.


%package license
Summary: license components for the libspatialindex package.
Group: Default

%description license
license components for the libspatialindex package.


%prep
%setup -q -n libspatialindex-1.9.3
cd %{_builddir}/libspatialindex-1.9.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1672182877
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake ..
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test

%install
export SOURCE_DATE_EPOCH=1672182877
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libspatialindex
cp %{_builddir}/libspatialindex-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libspatialindex/83cb62f2b17ba7c35533dceb4ed0d871e776e722
cp %{_builddir}/libspatialindex-%{version}/test/gtest/gtest-1.10.0/LICENSE %{buildroot}/usr/share/package-licenses/libspatialindex/5a2314153eadadc69258a9429104cd11804ea304
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/spatialindex/LineSegment.h
/usr/include/spatialindex/MVRTree.h
/usr/include/spatialindex/MovingPoint.h
/usr/include/spatialindex/MovingRegion.h
/usr/include/spatialindex/Point.h
/usr/include/spatialindex/RTree.h
/usr/include/spatialindex/Region.h
/usr/include/spatialindex/SpatialIndex.h
/usr/include/spatialindex/TPRTree.h
/usr/include/spatialindex/TimePoint.h
/usr/include/spatialindex/TimeRegion.h
/usr/include/spatialindex/Version.h
/usr/include/spatialindex/capi/BoundsQuery.h
/usr/include/spatialindex/capi/CountVisitor.h
/usr/include/spatialindex/capi/CustomStorage.h
/usr/include/spatialindex/capi/DataStream.h
/usr/include/spatialindex/capi/Error.h
/usr/include/spatialindex/capi/IdVisitor.h
/usr/include/spatialindex/capi/Index.h
/usr/include/spatialindex/capi/LeafQuery.h
/usr/include/spatialindex/capi/ObjVisitor.h
/usr/include/spatialindex/capi/Utility.h
/usr/include/spatialindex/capi/sidx_api.h
/usr/include/spatialindex/capi/sidx_config.h
/usr/include/spatialindex/capi/sidx_export.h
/usr/include/spatialindex/capi/sidx_impl.h
/usr/include/spatialindex/tools/PointerPool.h
/usr/include/spatialindex/tools/PoolPointer.h
/usr/include/spatialindex/tools/Tools.h
/usr/include/spatialindex/tools/rand48.h
/usr/lib64/libspatialindex.so
/usr/lib64/libspatialindex_c.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libspatialindex.so.6
/usr/lib64/libspatialindex.so.6.1.1
/usr/lib64/libspatialindex_c.so.6
/usr/lib64/libspatialindex_c.so.6.1.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libspatialindex/5a2314153eadadc69258a9429104cd11804ea304
/usr/share/package-licenses/libspatialindex/83cb62f2b17ba7c35533dceb4ed0d871e776e722
